INSERT INTO "public"."competency_templates" ("id", "role_type", "competency_name", "competency_code", "description", "category", "weightage", "calculation_formula", "icon", "max_score", "is_active", "sort_order", "created_at", "updated_at") VALUES 
('02ecf865-0da9-4f04-8b27-18bec8187144', 'field_executive', 'Territory Coverage', 'FSE_TERRITORY_COVERAGE', 'Measures how effectively you cover your assigned beats and retailers', 'productivity', '15.00', '{"formula":"unique_beats_visited / planned_beats * 100","metrics":["beats_planned","beats_visited","coverage_rate"],"data_sources":["beat_plans","visits"]}', 'Map', '100.00', true, '1', now(), now()), 
('22b84dea-8c71-41ac-bdf5-1d7335e19309', 'field_executive', 'Retailer Development', 'FSE_RETAILER_DEV', 'New retailer additions and reactivation of dormant accounts', 'development', '10.00', '{"formula":"(new_retailers + reactivated_retailers) / target * 100","metrics":["new_retailers","reactivated_retailers","dormant_converted"],"data_sources":["retailers","orders"]}', 'UserPlus', '100.00', true, '5', now(), now()), 
('2947e2b9-28f1-413b-aeec-48d015fcf0c6', 'field_manager', 'Coverage Management', 'FSM_COVERAGE', 'Overall territory and beat coverage by the team', 'productivity', '10.00', '{"formula":"avg(team_coverage_metrics)","metrics":["total_beats","beats_covered","retailers_visited","coverage_rate"],"data_sources":["beats","visits","retailers"]}', 'MapPin', '100.00', true, '6', now(), now()), 
('30960491-3599-44f5-9528-b0090bc6ab7b', 'field_manager', 'Team Productivity', 'FSM_TEAM_PRODUCTIVITY', 'Average productivity rate across team members', 'leadership', '20.00', '{"formula":"avg(team_members.productivity_rate)","metrics":["team_visits","team_productive_visits","avg_team_productivity"],"data_sources":["visits","orders","subordinates"]}', 'TrendingUp', '100.00', true, '2', now(), now()), 
('3956a2af-9ab7-4fe4-b14c-911e604f3fb7', 'field_manager', 'Talent Development', 'FSM_TALENT', 'Growth in team member performance over time', 'development', '15.00', '{"formula":"avg(team_score_growth)","metrics":["members_growing","members_declining","avg_growth_rate"],"data_sources":["user_monthly_scorecards"]}', 'Sparkles', '100.00', true, '5', now(), now()), 
('534eef9e-8ccd-4c24-9692-0725adaafad9', 'field_executive', 'Revenue Achievement', 'FSE_REVENUE', 'Achievement against revenue targets for the period', 'achievement', '25.00', '{"formula":"actual_revenue / target_revenue * 100","metrics":["target_revenue","actual_revenue","achievement_rate"],"data_sources":["orders","user_period_targets"]}', 'IndianRupee', '100.00', true, '3', now(), now()), 
('55654708-8ee3-4fbe-afff-7747f038c636', 'field_executive', 'Product Mix', 'FSE_PRODUCT_MIX', 'Selling focus products and maintaining healthy SKU diversity', 'achievement', '10.00', '{"formula":"(focus_product_revenue / total_revenue * 50) + (unique_skus_sold / target_skus * 50)","metrics":["focus_product_revenue","total_revenue","unique_skus","sku_diversity_score"],"data_sources":["orders","order_items","products"]}', 'Package', '100.00', true, '6', now(), now()), 
('78752e12-18d1-4ad8-a875-512fd4c30009', 'field_manager', 'Team Achievement', 'FSM_TEAM_ACHIEVEMENT', 'Overall revenue and target achievement of your team', 'leadership', '25.00', '{"formula":"avg(team_members.revenue_achievement)","metrics":["team_revenue","team_target","team_achievement_rate","members_on_target"],"data_sources":["user_performance_scores","subordinates"]}', 'Users', '100.00', true, '1', now(), now()), 
('79abb2ee-cc44-4c30-a802-0525a2f27edc', 'field_manager', 'Coaching Effectiveness', 'FSM_COACHING', 'Improvement in team member competency scores after coaching', 'development', '15.00', '{"formula":"avg(team_improvement_rate)","metrics":["coaching_sessions","members_improved","avg_score_improvement"],"data_sources":["user_competency_monthly_scores","competency_coaching_notes"]}', 'GraduationCap', '100.00', true, '3', now(), now()), 
('7c7980d8-9ae2-4d55-acdb-a67dd4ebb98b', 'field_manager', 'Planning Excellence', 'FSM_PLANNING', 'Quality of beat plans and adherence to planned coverage', 'discipline', '15.00', '{"formula":"avg(team_coverage_rate)","metrics":["plans_created","plans_executed","coverage_rate"],"data_sources":["beat_plans","visits"]}', 'Calendar', '100.00', true, '4', now(), now()), 
('87444dfc-06b6-443b-827e-4b90d16e035e', 'field_executive', 'Productivity', 'FSE_PRODUCTIVITY', 'Percentage of visits that result in successful orders', 'productivity', '20.00', '{"formula":"productive_visits / total_visits * 100","metrics":["total_visits","productive_visits","productivity_rate"],"data_sources":["visits","orders"]}', 'TrendingUp', '100.00', true, '2', now(), now()), 
('9a942427-991b-479f-8213-f7fedc650a36', 'field_executive', 'Visit Discipline', 'FSE_DISCIPLINE', 'Adherence to visit protocols including check-ins, photos, and timing', 'discipline', '15.00', '{"formula":"(checkin_compliance + photo_compliance + timing_score) / 3","metrics":["checkin_rate","photo_rate","avg_visit_duration","on_time_rate"],"data_sources":["visits","attendance"]}', 'Clock', '100.00', true, '4', now(), now()), 
('a0da058e-9de8-4986-bf64-9f6881baed43', 'field_executive', 'Collection Efficiency', 'FSE_COLLECTION', 'Timely collection of credit and maintaining healthy DSO', 'discipline', '5.00', '{"formula":"(on_time_collections / total_credit_orders * 100)","metrics":["credit_orders","collected_on_time","dso_days","overdue_amount"],"data_sources":["orders","payments"]}', 'Wallet', '100.00', true, '7', now(), now());