// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoxdosjkwqyuvccuwhzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFveGRvc2prd3F5dXZjY3V3aHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5ODUyOTYsImV4cCI6MjA4MjU2MTI5Nn0.KcKh1kvHtMJ0dUfgZeSwUK64vUDJZzgoXUSOzEVF5R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});